# ==============================================================================
# Workload: zabbix-proxy
# Architecture Domain: OSS Management
# Author: Kevin Oliveira
# ==============================================================================

